In [1]:
import pandas as pd

df_movies = pd.read_excel("Movies.xlsx")

df_movies.head(10)

,ID,Title,Release Date,Run Time,Genre,Director,Studio,Country,Language,Certificate,Budget,Box Office,Nominations,Oscar Wins
0,1,Jurassic Park,1993-06-11,126,Adventure,Steven Spielberg,Amblin Entertainment,United States,English,PG,63000000.0,1.029940e+09,3,3
1,2,Spider-Man,2002-05-03,121,Action,Sam Raimi,Marvel Entertainment,United States,English,12A,140000000.0,8.217086e+08,2,0
2,3,King Kong,2005-12-14,187,Adventure,Peter Jackson,WingNut Films,New Zealand,English,12A,207000000.0,5.505000e+08,4,3
3,5,Superman Returns,2006-07-14,154,Action,Bryan Singer,Legendary Pictures,United States,English,12A,204000000.0,3.910812e+08,1,0
4,6,Titanic,1998-01-23,194,Romance,James Cameron,20th Century Fox,United States,English,12,200000000.0,2.186772e+09,14,11
5,7,Evan Almighty,2007-06-22,96,Comedy,Tom Shadyac,Spyglass Entertainment,United States,English,PG,175000000.0,1.734188e+08,0,0
6,8,Waterworld,1995-07-28,135,Adventure,Kevin Reynolds,Gordon Company,United States,English,12,175000000.0,2.642182e+08,1,0
7,9,Pearl Harbor,2001-05-21,183,War,Michael Bay,Touchstone Pictures,United States,English,12,140000000.0,4.492209e+08,4,1
8,10,Transformers,2007-07-03,144,Science Fiction,Michael Bay,di Bonaventura Pictures,United States,English,12A,150000000.0,7.097098e+08,3,0
9,11,Harry Potter and the Order of the Phoenix,2007-07-11,138,Fantasy,David Yates,Heyday Films,United Kingdom,English,12A,150000000.0,9.398859e+08,0,0

In [8]:
df_movies.tail(2)

,ID,Title,Release Date,Run Time,Genre,Director,Studio,Country,Language,Certificate,Budget,Box Office,Nominations,Oscar Wins
1198,1677,In the Line of Fire,1993-07-09,128,Thriller,Wolfgang Peterson,Castle Rock Entertainment,United States,English,15,40000000.0,177000000.0,3,0
1199,1678,Outbreak,1995-03-10,128,Thriller,Wolfgang Peterson,Warner Bros. Pictures,United States,English,15,50000000.0,189800000.0,0,0

In [ ]:
df_movies.info()