In [1]:
import pandas as pd

df_movies = pd.read_excel('Movies.xlsx')
df_movies.head (10)

,ID,Title,Release Date,Run Time,Genre,Director,Studio,Country,Language,Certificate,Budget,Box Office,Nominations,Oscar Wins
0,1,Jurassic Park,1993-06-11,126,Adventure,Steven Spielberg,Amblin Entertainment,United States,English,PG,63000000.0,1.029940e+09,3,3
1,2,Spider-Man,2002-05-03,121,Action,Sam Raimi,Marvel Entertainment,United States,English,12A,140000000.0,8.217086e+08,2,0
2,3,King Kong,2005-12-14,187,Adventure,Peter Jackson,WingNut Films,New Zealand,English,12A,207000000.0,5.505000e+08,4,3
3,5,Superman Returns,2006-07-14,154,Action,Bryan Singer,Legendary Pictures,United States,English,12A,204000000.0,3.910812e+08,1,0
4,6,Titanic,1998-01-23,194,Romance,James Cameron,20th Century Fox,United States,English,12,200000000.0,2.186772e+09,14,11
5,7,Evan Almighty,2007-06-22,96,Comedy,Tom Shadyac,Spyglass Entertainment,United States,English,PG,175000000.0,1.734188e+08,0,0
6,8,Waterworld,1995-07-28,135,Adventure,Kevin Reynolds,Gordon Company,United States,English,12,175000000.0,2.642182e+08,1,0
7,9,Pearl Harbor,2001-05-21,183,War,Michael Bay,Touchstone Pictures,United States,English,12,140000000.0,4.492209e+08,4,1
8,10,Transformers,2007-07-03,144,Science Fiction,Michael Bay,di Bonaventura Pictures,United States,English,12A,150000000.0,7.097098e+08,3,0
9,11,Harry Potter and the Order of the Phoenix,2007-07-11,138,Fantasy,David Yates,Heyday Films,United Kingdom,English,12A,150000000.0,9.398859e+08,0,0

In [2]:
print(df_movies.columns, "\n")
df_movies.info()

Index(['ID', 'Title', 'Release Date', 'Run Time', 'Genre', 'Director',
       'Studio', 'Country', 'Language', 'Certificate', 'Budget', 'Box Office',
       'Nominations', 'Oscar Wins'],
      dtype='object')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            1200 non-null   int64
 1   Title         1200 non-null   object
 2   Release Date  1200 non-null   datetime64[ns]
 3   Run Time      1200 non-null   int64
 4   Genre         1200 non-null   object
 5   Director      1200 non-null   object
 6   Studio        1200 non-null   object
 7   Country       1199 non-null   object
 8   Language      1200 non-null   object
 9   Certificate   1200 non-null   object
 10  Budget        1076 non-null   float64
 11  Box Office    1083 non-null   float64
 12  Nominations   1200 non-null   int64
 13  Oscar Wins    1200 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(4), object(7)
memory usage: 131.4+ KB

In [3]:
df_movies[['Title', 'Genre', 'Box Office']]

                      Title            Genre    Box Office
0             Jurassic Park        Adventure  1.029940e+09
1                Spider-Man           Action  8.217086e+08
2                 King Kong        Adventure  5.505000e+08
3          Superman Returns           Action  3.910812e+08
4                   Titanic          Romance  2.186772e+09
...                     ...              ...           ...
1195     Samson and Delilah            Drama  2.560000e+07
1196  The NeverEnding Story          Fantasy  1.000000e+08
1197             Enemy Mine  Science Fiction  1.230000e+07
1198    In the Line of Fire         Thriller  1.770000e+08
1199               Outbreak         Thriller  1.898000e+08

[1200 rows x 3 columns]

In [4]:
df_movies[df_movies["Genre"] == "Action"]

,ID,Title,Release Date,Run Time,Genre,Director,Studio,Country,Language,Certificate,Budget,Box Office,Nominations,Oscar Wins
1,2,Spider-Man,2002-05-03,121,Action,Sam Raimi,Marvel Entertainment,United States,English,12A,140000000.0,821708551.0,2,0
3,5,Superman Returns,2006-07-14,154,Action,Bryan Singer,Legendary Pictures,United States,English,12A,204000000.0,391081192.0,1,0
17,19,Batman Begins,2005-06-15,141,Action,Christopher Nolan,Legendary Pictures,United States,English,12A,150000000.0,374218673.0,1,0
21,23,Lethal Weapon 4,1998-07-10,127,Action,Richard Donner,Silver Pictures,United States,English,15,100000000.0,285444603.0,0,0
24,26,Spider-Man 3,2007-05-04,139,Action,Sam Raimi,Marvel Entertainment,United States,English,12A,258000000.0,890871626.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1140,1619,Sin City: A Dame to Kill For,2014-08-19,102,Action,Robert Rodriguez,Dimension Films,United States,English,18,65000000.0,39400000.0,0,0
1142,1621,Ant-Man,2015-06-29,117,Action,Peyton Reed,Marvel Entertainment,United States,English,12A,130000000.0,519300000.0,0,0
1145,1624,The Wolverine,2013-07-16,126,Action,James Mangold,Marvel Entertainment,United States,English,12A,120000000.0,414800000.0,0,0
1162,1641,Bad Boys,1995-04-07,119,Action,Michael Bay,Jerry Bruckheimer Films,United States,English,18,23000000.0,141400000.0,0,0
1174,1653,Superman III,1983-06-17,125,Action,Richard Lester,Dovemead,United Kingdom,English,PG,39000000.0,80200000.0,0,0

In [5]:
df_movies[df_movies["Box Office"] > 1000000000]

,ID,Title,Release Date,Run Time,Genre,Director,Studio,Country,Language,Certificate,Budget,Box Office,Nominations,Oscar Wins
0,1,Jurassic Park,1993-06-11,126,Adventure,Steven Spielberg,Amblin Entertainment,United States,English,PG,63000000.0,1.029940e+09,3,3
4,6,Titanic,1998-01-23,194,Romance,James Cameron,20th Century Fox,United States,English,12,200000000.0,2.186772e+09,14,11
19,21,Pirates of the Caribbean: Dead Man's Chest,2006-07-06,151,Adventure,Gore Verbinski,Walt Disney Pictures,United States,English,12A,225000000.0,1.066180e+09,4,1
46,48,Star Wars: Episode I - The Phantom Menace,1999-05-19,133,Science Fiction,George Lucas,Lucasfilm,United States,English,U,115000000.0,1.027000e+09,3,0
71,73,The Lord of the Rings: Return of the King,2003-12-17,201,Fantasy,Peter Jackson,WingNut Films,New Zealand,English,12A,94000000.0,1.119930e+09,11,11
262,270,Transformers: Age of Extinction,2014-06-27,165,Science Fiction,Michael Bay,di Bonaventura Pictures,United States,English,12A,210000000.0,1.091000e+09,0,0
272,280,Frozen,2013-11-27,102,Animation,Chris Buck,Walt Disney Pictures,United States,English,PG,150000000.0,1.276000e+09,2,2
273,281,Iron Man 3,2013-05-03,130,Action,Shane Black,Marvel Entertainment,United States,English,12A,200000000.0,1.215000e+09,1,0
282,290,The Avengers,2012-05-04,143,Action,Joss Whedon,Marvel Entertainment,United States,English,12A,220000000.0,1.520000e+09,1,0
283,291,Skyfall,2012-10-26,143,Thriller,Sam Mendes,Eon Productions,United Kingdom,English,12A,150000000.0,1.109000e+09,5,2
284,292,The Dark Knight Rises,2012-07-20,165,Action,Christopher Nolan,Legendary Pictures,United States,English,12A,230000000.0,1.085000e+09,0,0
285,293,The Hobbit: An Unexpected Journey,2012-12-14,169,Fantasy,Peter Jackson,WingNut Films,New Zealand,English,12A,200000000.0,1.021000e+09,3,0
292,300,Harry Potter and the Deathly Hallows - Part 2,2011-07-15,130,Fantasy,David Yates,Heyday Films,United Kingdom,English,12A,250000000.0,1.342000e+09,3,0
293,301,Transformers: Dark of the Moon,2011-06-29,157,Science Fiction,Michael Bay,di Bonaventura Pictures,United States,English,12A,195000000.0,1.124000e+09,3,0
294,302,Pirates of the Caribbean: On Stranger Tides,2011-05-20,137,Adventure,Rob Marshall,Walt Disney Pictures,United States,English,12A,378500000.0,1.046000e+09,0,0
302,310,Toy Story 3,2010-06-18,103,Animation,Lee Unkrich,Pixar Animation Studios,United States,English,U,200000000.0,1.063000e+09,5,2
303,311,Alice in Wonderland,2010-02-25,108,Fantasy,Tim Burton,Walt Disney Pictures,United Kingdom,English,PG,150000000.0,1.025000e+09,3,2
312,320,Avatar,2009-12-17,161,Science Fiction,James Cameron,Lightstorm Entertainment,United States,English,12A,237000000.0,2.788000e+09,9,3
322,330,The Dark Knight,2008-07-24,152,Action,Christopher Nolan,Legendary Pictures,United States,English,12A,185000000.0,1.005000e+09,8,2
646,1120,Star Wars: The Force Awakens,2015-12-17,136,Science Fiction,J. J. Abrams,Lucasfilm,United States,English,12A,306000000.0,2.066000e+09,5,0
647,1121,Jurassic World,2015-06-12,124,Adventure,Colin Trevorrow,Amblin Entertainment,United States,English,12A,150000000.0,1.670000e+09,0,0
648,1122,Furious 7,2015-04-03,137,Action,James Wan,Original Film,United States,English,12A,190000000.0,1.516000e+09,0,0
649,1123,Avengers: Age of Ultron,2015-05-01,141,Action,Joss Whedon,Marvel Entertainment,United States,English,12A,250000000.0,1.405000e+09,0,0
650,1124,Minions,2015-06-11,91,Animation,Pierre Coffin,Illumination Entertainment,United States,English,U,74000000.0,1.159000e+09,0,0
656,1130,Captain America: Civil War,2016-05-06,147,Action,Anthony Russo,Marvel Entertainment,United States,English,12A,250000000.0,1.153000e+09,0,0
657,1131,Finding Dory,2016-06-17,97,Animation,Andrew Stanton,Pixar Animation Studios,United States,English,U,200000000.0,1.025000e+09,0,0
658,1132,Zootopia,2016-04-04,108,Animation,Byron Howard,Walt Disney Pictures,United States,English,PG,150000000.0,1.024000e+09,0,0

In [6]:
df_movies["Profit"] = df_movies["Box Office"] - df_movies["Budget"]
print(df_movies.columns)

Index(['ID', 'Title', 'Release Date', 'Run Time', 'Genre', 'Director',
       'Studio', 'Country', 'Language', 'Certificate', 'Budget', 'Box Office',
       'Nominations', 'Oscar Wins', 'Profit'],
      dtype='object')

In [7]:
df_movies["Success"] = df_movies["Profit"].apply(lambda x: "Hit" if x > 100000000 else "Flop")
print(df_movies[["Title", "Profit", "Success"]])

                      Title        Profit Success
0             Jurassic Park  9.669399e+08     Hit
1                Spider-Man  6.817086e+08     Hit
2                 King Kong  3.435000e+08     Hit
3          Superman Returns  1.870812e+08     Hit
4                   Titanic  1.986772e+09     Hit
...                     ...           ...     ...
1195     Samson and Delilah  2.270000e+07    Flop
1196  The NeverEnding Story  7.300000e+07    Flop
1197             Enemy Mine -1.670000e+07    Flop
1198    In the Line of Fire  1.370000e+08     Hit
1199               Outbreak  1.398000e+08     Hit

[1200 rows x 3 columns]

In [8]:
df_movies[df_movies["Budget"] > 200000000] [["Title", "Profit", "Budget"]]

                                              Title        Profit       Budget
2                                         King Kong  3.435000e+08  207000000.0
3                                  Superman Returns  1.870812e+08  204000000.0
12         Pirates of the Caribbean: At World's End  6.634204e+08  300000000.0
19       Pirates of the Caribbean: Dead Man's Chest  8.411797e+08  225000000.0
24                                     Spider-Man 3  6.328716e+08  258000000.0
262                 Transformers: Age of Extinction  8.810000e+08  210000000.0
263       The Hobbit: The Battle of the Five Armies  7.051000e+08  250000000.0
269                        The Amazing Spider-Man 2  4.540000e+08  255000000.0
275             The Hobbit: The Desolation of Smaug  7.334000e+08  225000000.0
280                                    Man of Steel  4.430000e+08  225000000.0
282                                    The Avengers  1.300000e+09  220000000.0
284                           The Dark Knight Rises  8.550000e+08  230000000.0
288                          The Amazing Spider-Man  5.279000e+08  230000000.0
291                                  Men in Black 3  4.090000e+08  215000000.0
292   Harry Potter and the Deathly Hallows - Part 2  1.092000e+09  250000000.0
294     Pirates of the Caribbean: On Stranger Tides  6.675000e+08  378500000.0
304   Harry Potter and the Deathly Hallows - Part 1  7.103000e+08  250000000.0
309                                         Tangled  3.318000e+08  260000000.0
312                                          Avatar  2.551000e+09  237000000.0
313          Harry Potter and the Half-Blood Prince  6.844000e+08  250000000.0
330        The Chronicles of Narnia: Prince Caspian  1.947000e+08  225000000.0
646                    Star Wars: The Force Awakens  1.760000e+09  306000000.0
649                         Avengers: Age of Ultron  1.155000e+09  250000000.0
651                                         Spectre  6.357000e+08  245000000.0
656                      Captain America: Civil War  9.030000e+08  250000000.0
660              Batman v Superman: Dawn of Justice  6.233000e+08  250000000.0
787                                        47 Ronin -7.320000e+07  225000000.0
800                                      Battleship  8.300000e+07  220000000.0
855                                     John Carter -6.590000e+07  350000000.0
884                           X-Men: The Last Stand  2.494000e+08  210000000.0
1053                                   Man of Steel  4.430000e+08  225000000.0

In [9]:
df_movies[(df_movies["Genre"] == "Adventure") & (df_movies["Run Time"] < 120)]

,ID,Title,Release Date,Run Time,Genre,Director,Studio,Country,Language,Certificate,Budget,Box Office,Nominations,Oscar Wins,Profit,Success
126,128,300,2007-03-23,117,Adventure,Zack Snyder,Legendary Pictures,United States,English,15,65000000.0,456000000.0,0,0,391000000.0,Hit
149,151,The Last of the Mohicans,1992-09-25,112,Adventure,Michael Mann,Morgan Creek Productions,United States,English,12,40000000.0,75505856.0,1,1,35505856.0,Flop
173,175,Indiana Jones and the Temple of Doom,1984-05-23,118,Adventure,Steven Spielberg,Lucasfilm,United States,English,12,28170000.0,333107271.0,2,1,304937271.0,Hit
195,197,Raiders of the Lost Ark,1981-06-12,115,Adventure,Steven Spielberg,Lucasfilm,United States,English,PG,18000000.0,389900000.0,9,5,371900000.0,Hit
253,259,King Kong,1933-04-07,100,Adventure,Merian C. Cooper,RKO Radio Pictures,United States,English,PG,672000.0,2847000.0,0,0,2175000.0,Flop
334,343,Night at the Museum,2006-12-22,108,Adventure,Shawn Levy,Dune Entertainment,United States,English,PG,110000000.0,574500000.0,0,0,464500000.0,Hit
350,359,Jurassic Park III,2001-07-18,92,Adventure,Joe Johnston,Amblin Entertainment,United States,English,PG,93000000.0,368800000.0,0,0,275800000.0,Hit
384,394,Jumanji,1995-12-15,104,Adventure,Joe Johnston,Interscope Communications,United States,English,PG,65000000.0,262800000.0,0,0,197800000.0,Hit
422,434,"Honey, I Shrunk the Kids",1989-06-23,94,Adventure,Joe Johnston,Walt Disney Pictures,United States,English,U,18000000.0,222700000.0,0,0,204700000.0,Hit
429,441,Crocodile Dundee II,1988-05-25,112,Adventure,John Cornell,Paramount Pictures,Australia,English,PG,14000000.0,239600000.0,0,0,225600000.0,Hit
445,458,The Golden Child,1986-12-12,94,Adventure,Michael Ritchie,Eddie Murphy Productions,United States,English,PG,25000000.0,79800000.0,0,0,54800000.0,Flop
452,466,The Jewel of the Nile,1985-12-11,107,Adventure,Lewis Teague,20th Century Fox,United States,English,PG,25000000.0,96700000.0,0,0,71700000.0,Flop
453,468,The Goonies,1985-06-07,114,Adventure,Richard Donner,Amblin Entertainment,United States,English,PG,19000000.0,61500000.0,0,0,42500000.0,Flop
460,476,Romancing the Stone,1984-03-30,106,Adventure,Robert Zemeckis,20th Century Fox,United States,English,12,10000000.0,86500000.0,1,0,76500000.0,Flop
539,589,Bedknobs and Broomsticks,1971-10-07,117,Adventure,Robert Stevenson,Walt Disney Pictures,United Kingdom,English,U,20000000.0,18530000.0,5,1,-1470000.0,Flop
601,709,The Vikings,1958-06-28,116,Adventure,Richard Fleischer,United Artists,United States,English,PG,3500000.0,6000000.0,0,0,2500000.0,Flop
621,766,Ivanhoe,1952-07-31,106,Adventure,Richard Thorpe,Metro-Goldwyn-Mayer,United Kingdom,English,U,3842000.0,10878000.0,3,0,7036000.0,Flop
626,779,The African Queen,1951-12-23,105,Adventure,John Huston,Horizon Pictures,United States,English,U,1000000.0,10750000.0,4,1,9750000.0,Flop
629,784,King Solomon's Mines,1950-11-24,103,Adventure,Compton Bennett,Metro-Goldwyn-Mayer,United States,English,PG,2300000.0,15100000.0,3,2,12800000.0,Flop
659,1133,The Jungle Book,2016-04-15,105,Adventure,Jon Favreau,Walt Disney Pictures,United States,English,PG,175000000.0,966500000.0,0,0,791500000.0,Hit
669,1143,Captain Blood,1935-12-28,119,Adventure,Michael Curtiz,Cosmopolitan Productions,United States,English,PG,1200000.0,3100000.0,5,0,1900000.0,Flop
670,1144,The Adventures of Robin Hood,1938-05-14,102,Adventure,Michael Curtiz,Warner Bros. Pictures,United States,English,U,2033000.0,3981000.0,4,3,1948000.0,Flop
671,1145,The Charge of the Light Brigade,1936-10-20,115,Adventure,Michael Curtiz,Warner Bros. Pictures,United States,English,PG,1330000.0,3300000.0,3,1,1970000.0,Flop
738,1212,The Mummy: Tomb of the Dragon Emperor,2008-08-01,111,Adventure,Rob Cohen,Relativity Media,United States,English,12A,145000000.0,401100000.0,0,0,256100000.0,Hit
744,1218,Clash of the Titans,2010-04-02,106,Adventure,Louis Leterrier,Legendary Pictures,United States,English,12A,125000000.0,493200000.0,0,0,368200000.0,Hit
745,1219,Clash of the Titans,1981-06-12,118,Adventure,Desmond Davis,Metro-Goldwyn-Mayer,United Kingdom,English,12,15000000.0,41000000.0,0,0,26000000.0,Flop
748,1222,Zu Warriors from the Magic Mountain,1983-02-05,98,Adventure,Hark Tsui,Golden Harvest,Hong Kong,Cantonese,PG,NaN,NaN,0,0,NaN,Flop
818,1292,Lone Wolf and Cub: Sword of Vengeance,1972-04-01,83,Adventure,Kenji Misumi,Toho Company,Japan,Japanese,18,NaN,NaN,0,0,NaN,Flop
819,1293,Lone Wolf and Cub: Baby Cart at the River Styx,1972-04-27,85,Adventure,Kenji Misumi,Toho Company,Japan,Japanese,18,NaN,NaN,0,0,NaN,Flop
820,1294,Lone Wolf and Cub: Baby Cart to Hades,1972-09-02,89,Adventure,Kenji Misumi,Toho Company,Japan,Japanese,18,NaN,NaN,0,0,NaN,Flop
821,1295,Lone Wolf and Cub: Baby Cart in Peril,1972-11-01,81,Adventure,Buichi Saito,Toho Company,Japan,Japanese,18,NaN,NaN,0,0,NaN,Flop
822,1296,Lone Wolf and Cub: Baby Cart in the Land of De...,1973-08-11,89,Adventure,Kenji Misumi,Toho Company,Japan,Japanese,18,NaN,NaN,0,0,NaN,Flop
823,1297,Lone Wolf and Cub: White Heaven in Hell,1974-04-24,84,Adventure,Yoshiyuki Kuroda,Toho Company,Japan,Japanese,18,NaN,NaN,0,0,NaN,Flop
857,1331,Solomon Kane,2009-12-23,104,Adventure,Michael J. Bassett,Davis Entertainment,France,English,15,40000000.0,19400000.0,0,0,-20600000.0,Flop
1035,1511,Bill & Ted's Excellent Adventure,1989-02-17,89,Adventure,Stephen Herek,Interscope Communications,United States,English,PG,10000000.0,40500000.0,0,0,30500000.0,Flop
1036,1512,Bill & Ted's Bogus Journey,1991-07-19,93,Adventure,Peter Hewitt,Interscope Communications,United States,English,PG,20000000.0,38000000.0,0,0,18000000.0,Flop
1130,1608,Black Death,2010-06-11,101,Adventure,Christopher Smith,Egoli Tossell Film,Germany,English,15,NaN,272445.0,0,0,NaN,Flop
1149,1628,The Three Musketeers,1993-11-12,105,Adventure,Stephen Herek,Walt Disney Pictures,United States,English,PG,30000000.0,53900000.0,0,0,23900000.0,Flop
1165,1644,The Eagle,2011-03-25,114,Adventure,Kevin Macdonald,FilmFour Productions,United Kingdom,English,12A,25000000.0,35500000.0,0,0,10500000.0,Flop
1167,1646,Centurion,2010-04-23,97,Adventure,Neil Marshall,UK Film Council,United Kingdom,English,15,12000000.0,6168000.0,0,0,-5832000.0,Flop
1171,1650,One Million Years B.C.,1966-12-30,100,Adventure,Don Chaffey,Hammer Film Productions,United Kingdom,English,PG,500000.0,8000000.0,0,0,7500000.0,Flop
1172,1651,The Three Musketeers,1973-12-11,105,Adventure,Richard Lester,20th Century Fox,United Kingdom,English,U,NaN,10100000.0,0,0,NaN,Flop
1173,1652,The Return of the Musketeers,1989-04-19,102,Adventure,Richard Lester,Universal Pictures,United Kingdom,English,PG,NaN,NaN,0,0,NaN,Flop
1175,1654,The Four Musketeers,1974-10-31,108,Adventure,Richard Lester,20th Century Fox,United Kingdom,English,PG,NaN,8760000.0,1,0,NaN,Flop
1181,1660,King Solomon's Mines,1985-11-22,100,Adventure,J. Lee Thompson,Cannon Productions,United States,English,PG,11000000.0,15057000.0,0,0,4057000.0,Flop
1182,1661,King Solomon's Mines,1937-06-17,80,Adventure,Robert Stevenson,Gaumont,United Kingdom,English,U,NaN,NaN,0,0,NaN,Flop

In [10]:
df_movies[(df_movies["Release Date"].dt.year > 2010) & (df_movies["Box Office"] > 500000000)].count()

ID              71
Title           71
Release Date    71
Run Time        71
Genre           71
Director        71
Studio          71
Country         71
Language        71
Certificate     71
Budget          71
Box Office      71
Nominations     71
Oscar Wins      71
Profit          71
Success         71
dtype: int64

In [11]:
df_movies["Box Office"].mean()

np.float64(234237189.95198524)

In [12]:
df_movies["Genre"].value_counts()

Genre
Action             166
Comedy             134
Thriller           111
Science Fiction    110
Drama              108
Adventure           92
Animation           70
Martial Arts        67
Crime               63
Fantasy             46
War                 40
Western             37
Horror              26
Biography           25
Musical             23
Romance             22
History             13
Sport                9
Mystery              8
Disaster             8
Romantic Comedy      8
Family               6
Awful                5
Documentary          3
Name: count, dtype: int64

In [13]:
max_profit_index = df_movies['Profit'].idxmax()
max_profit_movie = df_movies.loc[max_profit_index, ['Title', 'Profit']]
print(max_profit_movie)

Title           Avatar
Profit    2551000000.0
Name: 312, dtype: object

In [14]:
df_movies.sort_values(by="Box Office", ascending=False).head(5)[["Title", "Box Office"]]

                            Title    Box Office
312                        Avatar  2.788000e+09
4                         Titanic  2.186772e+09
646  Star Wars: The Force Awakens  2.066000e+09
647                Jurassic World  1.670000e+09
282                  The Avengers  1.520000e+09

In [15]:
df_movies.groupby("Genre")["Box Office"].sum()

Genre
Action             4.524634e+10
Adventure          2.372770e+10
Animation          3.566717e+10
Awful              3.343716e+09
Biography          4.196324e+09
Comedy             1.952645e+10
Crime              3.835477e+09
Disaster           1.875852e+09
Documentary        3.482937e+07
Drama              9.311047e+09
Family             1.110300e+09
Fantasy            1.993374e+10
History            1.220848e+09
Horror             3.160869e+09
Martial Arts       2.617629e+09
Musical            2.528157e+09
Mystery            2.637740e+09
Romance            5.537656e+09
Romantic Comedy    1.117590e+09
Science Fiction    3.770238e+10
Sport              1.169300e+09
Thriller           2.241557e+10
War                3.417228e+09
Western            2.344957e+09
Name: Box Office, dtype: float64

In [16]:
pivot_table = df_movies.pivot_table(
    values=['Budget', 'Box Office'], 
    index=['Genre', 'Country'], 
    aggfunc='mean')
pivot_table

                          Box Office        Budget
Genre   Country
Action  Australia       1.345750e+08  4.122500e+07
        France          5.189000e+07  2.132000e+07
        Hong Kong                NaN  4.500000e+06
        Japan           1.972500e+07  2.575000e+06
        United Kingdom  2.190857e+08  5.842857e+07
...                              ...           ...
War     Japan           2.950000e+07  2.550000e+07
        United Kingdom  3.553000e+07  1.291667e+07
        United States   1.078522e+08  3.512259e+07
Western Italy           1.498038e+07  1.756250e+06
        United States   7.371083e+07  2.068270e+07

[86 rows x 2 columns]

In [17]:
df_movies[df_movies["Genre"] == "Comedy"].to_excel("Comedy_Movies.xlsx", index=False)

In [18]:
df_movies[df_movies["Run Time"] > 150].to_csv("Long_Movies.csv", index=False)

In [25]:
diretores_count = df_movies['Director'].value_counts()
print(diretores_count)
top_3_diretores = diretores_count.head(3).index

Director
Steven Spielberg       25
Ridley Scott           19
Martin Scorsese        18
Clint Eastwood         16
John Woo               12
                       ..
Lasse Hallstrom         1
Anthony Minghella       1
Catherine Hardwicke     1
Nicholas Ray            1
Les Mayfield            1
Name: count, Length: 482, dtype: int64

In [26]:
df_top_diretores = df_movies[df_movies['Director'].isin(top_3_diretores)]

resultado = df_top_diretores.groupby('Director').agg(
    Total_Filmes=('Title', 'count'),
    Soma_Box_Office=('Box Office', 'sum'),
    Soma_Budget=('Budget', 'sum'),
    Media_Run_Time=('Run Time', 'mean')
)
print(resultado)

                  Total_Filmes  Soma_Box_Office   Soma_Budget  Media_Run_Time
Director
Martin Scorsese             18     2.080441e+09  9.696000e+08      143.444444
Ridley Scott                19     3.872053e+09  1.459000e+09      133.052632
Steven Spielberg            25     9.063193e+09  1.471120e+09      136.760000

In [27]:
df_movies['Release Date'] = pd.to_datetime(df_movies['Release Date'], errors='coerce')

df_movies['Decade'] = (df_movies['Release Date'].dt.year // 10 * 10).astype(str) + 's'

resultado_decada_genero = df_movies.groupby(['Decade', 'Genre']).agg(
    Total_Filmes=('Title', 'count'),
    Media_Box_Office=('Box Office', 'mean')
)

print(resultado_decada_genero)

                        Total_Filmes  Media_Box_Office
Decade Genre
1920s  Comedy                      1      2.500000e+06
       Science Fiction             1               NaN
1930s  Adventure                   5      3.307000e+06
       Animation                   1      1.849255e+08
       Comedy                      1      9.000000e+06
...                              ...               ...
2010s  Science Fiction            30      5.000586e+08
       Sport                       1      9.820000e+07
       Thriller                   21      2.584506e+08
       War                         1      1.548000e+08
       Western                     5      2.486250e+08

[153 rows x 2 columns]